# Configuration default values.
# - These values can be overwritten with a custom `config.yml` in the repository base directory.
# - In the path settings, `./` denotes the repository base directory and is replaced upon loading.
paths:
  additional_data: []
  data: ./data
  supplementary_data: ./data/supplementary_data
  database: ./data/database.sqlite
  results: ./results
multiprocessing:
  run_parallel: false  # Currently not used.
optimization:
  solver_name: gurobi  # Must be valid input string for Pyomo's `SolverFactory`.
  show_solver_output: true  # If True, activate verbose solver output.
tests:
  scenario_name: create_level8_4zones_a  # Defines scenario which is considered in tests.
  show_plots: true  # If True, tests may produce plots.
logs:
  level: info  # Choices: `debug`, `info`, `warn`, `error`.
  format: '%(asctime)s | %(levelname)s | %(name)s | %(message)s'
plots:
  matplotlib_style: seaborn-colorblind
  plotly_font_family: Arial
  plotly_font_size: 15
  plotly_figure_width: 1000
  plotly_figure_height: 500
